added ability to create initrd added clean function verified boot autogenerated /etc/terminfo

diff --git a/bin/goo-make-initrd b/bin/goo-make-initrd
--- a/bin/goo-make-initrd
+++ b/bin/goo-make-initrd
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
+# TODO add file header
 
+# TODO allow these to be passed by params
 KEYFILE=/root/test.crypt
 KEYDEVNAME=testkey2
 
@@ -23,6 +25,7 @@ verbose=false
 ###########################
 
 # internal tracelog function
+# TODO add function header
 _traceback() {
     local -i start=$(( ${1:-0} + 1 ))
     local -i end=${#BASH_SOURCE[@]}
@@ -38,6 +41,7 @@ _traceback() {
     done
 }
 
+# TODO add function header
 # usage: die <error string> [traces nb=1]
 _die() {
     {   echo '---'
@@ -48,16 +52,19 @@ _die() {
     exit 2
 }
 
+# TODO add function header
 _echo() {
   echo -e " * $1"
   return 0
 }
 
+# TODO add function header
 _vecho() {
-  $verbose && echo " > $1"
+  $verbose && echo " *     $1"
   return 0
 }
 
+# TODO add function header
 _usage() {
   # valid formats
   #   [ -a | --alpha ]
@@ -68,6 +75,8 @@ _usage() {
      [ -h | --help ]    show this screen
      [ -v | --verbose ] increase output
   Valid actions:
+     initrd:       alias for make-initrd
+     make-initrd:  create a new initrd file
      make-keyfile: create an encrypted keyfile
      clean:        clean up directories generated during build for initrd
 EOF
@@ -79,6 +88,7 @@ EOF
 # command line argument processing
 #
 ###########################
+# TODO add function header
 _parse_ags_main() {
 
   # valid formats
@@ -119,25 +129,29 @@ _parse_ags_main() {
 # actions
 #
 ###########################
+# TODO add function header
 _action() {
   _vecho "called _action(): $action"
 
   case $1 in
-    make-keyfile)   _make-keyfile ; shift   ;;
-    clean)          _clean        ; shift   ;;
+    initrd)               _make-initrd  ; shift   ;;
+    make-initrd)          _make-initrd  ; shift   ;;
+    make-keyfile|initrd)  _make-keyfile ; shift   ;;
+    clean)                _clean        ; shift   ;;
     *) >&2 echo Unsupported action: $1
        _usage ;;
   esac
   return 0
 }
 
+# TODO add function header
 _clean() {
   source /etc/genkernel.conf
   rm -rf ${INITRAMFS_OVERLAY}/{usr/lib64,usr/bin,lib64,lib,bin,etc/initrd.d,usr,sbin} || _die "issue removing directories"
   return 0
 }
 
-# TODO: update comments
+# TODO add function header
 _make-keyfile() {
 
   _vecho "called _make-keyfile()"
@@ -169,6 +183,66 @@ _make-keyfile() {
 
   cryptsetup luksClose "$KEYDEVNAME"
   _vecho "closed $KEYDEVNAME"
+
+  return 0
+}
+
+# TODO add function header
+_make-initrd() {
+
+  _vecho "called _make-initrd()"
+
+  # TODO move these to the top
+  # TODO allow additional apps via command line params
+  # TODO allow additional apps via configuration file
+  apps="fsck.zfs dialog htop nano reboot zed modprobe nano mount.zfs shutdown zfs zpool column rsync blkid nvme"
+
+  # TODO allow INITRAMFS_OVERLAY variable to be set by command line parameters
+  source /etc/genkernel.conf
+
+  # TODO ensure INITRAMFS_OVERLAY is set and valid before using
+
+  _echo "creating initramfs"
+  # TODO this is a crude way of finding the most recently built kernel
+  NAME=$(ls -tr1 /lib/modules | tail -n 1)
+
+  _vecho "INITRAMFS_OVERLAY: ${INITRAMFS_OVERLAY}"
+  rm -rf "${INITRAMFS_OVERLAY}"/{usr/lib64,usr/bin,lib64,lib,bin,etc/initrd.d,usr,sbin}
+  mkdir -p "${INITRAMFS_OVERLAY}"/{usr/lib64,usr/bin,lib64,lib,bin,etc/initrd.d}
+
+  _vecho "copying modules (zfs, etc) for kernel"
+  rsync -r --delete --quiet /lib/modules "$INITRAMFS_OVERLAY"/lib/
+
+  _vecho "copying apps"
+  mkdir -p "$INITRAMFS_OVERLAY"/sbin/
+  # TODO refactor: why change directory?
+  pushd "$INITRAMFS_OVERLAY"/sbin/
+  rm -rf "$INITRAMFS_OVERLAY"/sbin/*
+  for app in $apps; do
+    _vecho "including $app"
+    cp -v $(which $app) .
+  done
+
+  _vecho "copying libs (libzfs, etc) for bins"
+  # TODO refactor, this line is too long
+  for i in *; do lddtree -l $(which "$i" 2>/dev/null) 2>/dev/null ;done | grep -v ^/sbin/ | grep lib64 | sort | uniq | while read line ; do cp $line "$INITRAMFS_OVERLAY"/lib64/; done
+  # TODO this is gentoo-dependent ... so in genkernel
+  cp /usr/lib/gcc/$(eselect gcc show | sed 's:\(.*\)-:\1/:g')/libgcc_s.so.1 "$INITRAMFS_OVERLAY"/lib64/
+  popd # refactor out with pushd above
+
+  _vecho "including ncurses libs"
+  mkdir -p "$INITRAMFS_OVERLAY"/etc/
+  rm -rf "$INITRAMFS_OVERLAY"/etc/terminfo
+  find /lib64/ -iname "*libncurses*" -exec cp {} "$INITRAMFS_OVERLAY"/lib64/ \; || die "failed to copy ncurses"
+
+  # TODO ensure terminfo directory exists
+  cp -r /usr/share/terminfo "$INITRAMFS_OVERLAY"/etc/ || die "failed to copy terminfo"
+
+  # TODO support separate genkernel options
+  # TODO    * by variable in file
+  # TODO    * by command line arguments
+  # TODO    * by config file
+  genkernel --install --zfs --ssh --ssh-authorized-keys-file=/root/.ssh/authorized_keys --luks --bootloader=grub2 --mountboot --no-splash initramfs || die "genkernel failed to build initrd with overlay"
 
   return 0
 }
